### ISSUE TITLE
Запрос

### ISSUE THREAD

**Issue by cybercent** [move/samples#1]
Здравствуйте Александр. У меня есть проект с открытым исходным кодом под названием «MOVE», и мне было интересно, не захотите ли вы изменить имя своего дескриптора github на что-то другое, чтобы мы могли использовать его для проекта. За ваши неприятности я готов компенсировать вам подарочную карту Amazon.

**Comment by dedtesla** [comment]
Здравствуйте. Не вопрос, поменял. Ничего не надо компенсировать.
